# Generated by Django 5.2.5 on 2025-08-17 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('users', '0004_profile_moedas'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='equipped_capacete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.storeitem'),
        ),
        migrations.AddField(
            model_name='profile',
            name='equipped_ferramenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.storeitem'),
        ),
        migrations.AddField(
            model_name='profile',
            name='equipped_luva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.storeitem'),
        ),
    ]
