# Generated by Django 5.2.5 on 2025-08-17 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_profile_moedas'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('item_type', models.CharField(choices=[('capacete', 'Capacete'), ('luva', 'Luva'), ('ferramenta', 'Ferramenta')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='users.profile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.storeitem')),
            ],
        ),
    ]
