# Generated by Django 5.2.5 on 2025-08-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='asset_url',
            field=models.CharField(blank=True, help_text='Ex: capacete_azul.png', max_length=200),
        ),
    ]
