# Generated by Django 5.2.5 on 2025-08-17 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('activity_type', models.CharField(choices=[('missao', 'Missão'), ('quiz', 'Quiz'), ('desafio', 'Desafio')], max_length=10)),
                ('order', models.PositiveIntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='courses.module')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
